"""Negotiating one shot's generation parameters against what the
configured provider actually supports.

This exists because the shot PLAN and the provider's CAPABILITIES are
written by different authorities and do not have to agree. The adaptation
schema lets a shot be 2-8 seconds because that is what reads well on
screen; Veo, driven by character references, generates exactly 8. Before
this module the worker hardcoded `360p` and passed the planned duration
straight through, so every real-provider shot failed `validate_request`
before a single frame existed -- the fake tier's numbers were quietly
standing in for a negotiation that was never written.

Three rules, in order of how much they matter:

1. **Never silently generate something other than what was approved.**
   A shot planned at 3s that comes back as 8s is not a rounding error, it
   is a different film. The difference is computed here so the approval
   gate can show it BEFORE any money is spent, rather than the operator
   discovering it in the finished cut.
2. **Never fight a provider over something that does not matter.** The
   resolution constant was written for the fake tier's cheap 360p. A real
   provider that only serves 720p should simply be honored.
3. **Never send an unapproved reference into paid generation.** Approval
   is what the CHARACTER_REVIEW gate means; this re-checks it at the last
   possible moment, because config and approvals can change between the
   gate and the worker picking the shot up.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from reel_harness.pipeline.reference_prompt import REFERENCE_VIEWS

# The views handed to a video provider as character references, in
# priority order. Face first because it carries identity most densely;
# wardrobe last because a garment is the easiest thing for a prompt to
# restate in words. A provider that accepts fewer than four takes the
# first N of these, never an arbitrary subset.
REFERENCE_PRIORITY = tuple(view.value for view in REFERENCE_VIEWS)


class GenerationPlanConflict(ValueError):
    """The shot plan cannot be generated by this provider at all -- raised
    at the approval gate so the operator learns before spending, and
    defensively in the worker."""


@dataclass(frozen=True)
class ShotGenerationParameters:
    """What will actually be requested, alongside what was planned, so a
    caller can report the difference instead of hiding it."""

    duration_sec: float
    resolution: str
    planned_duration_sec: float

    @property
    def duration_differs(self) -> bool:
        return self.duration_sec != self.planned_duration_sec

    @property
    def extra_seconds(self) -> float:
        return round(self.duration_sec - self.planned_duration_sec, 3)


def resolve_resolution(capabilities, preferred: str) -> str:
    """The resolution to request. Prefers the caller's default when the
    provider supports it; otherwise accepts the provider's own when there
    is exactly one to accept. Two or more supported resolutions with no
    match is genuinely ambiguous and is refused rather than guessed."""
    supported = capabilities.supported_resolutions
    if not supported:
        raise GenerationPlanConflict(
            "provider declares no supported resolutions -- it cannot generate anything"
        )
    if preferred in supported:
        return preferred
    if len(supported) == 1:
        return next(iter(supported))
    raise GenerationPlanConflict(
        f"provider does not support {preferred!r} and offers several alternatives "
        f"({', '.join(sorted(supported))}) -- no single choice is obviously right"
    )


def resolve_duration(capabilities, planned_sec: float) -> float:
    """The duration to request for a shot planned at `planned_sec`.

    An exact match is used as-is. Otherwise the SHORTEST supported
    duration that still covers the plan is chosen -- generating less than
    the beat needs would cut the shot short, which is a worse failure
    than generating a little extra. A plan longer than anything the
    provider offers is refused: silently shortening a shot changes the
    film."""
    supported = capabilities.supported_durations_sec
    if not supported:
        raise GenerationPlanConflict(
            "provider declares no supported durations -- it cannot generate anything"
        )
    if planned_sec in supported:
        return planned_sec
    longer = sorted(d for d in supported if d > planned_sec)
    if longer:
        return longer[0]
    raise GenerationPlanConflict(
        f"shot is planned at {planned_sec}s but the provider generates at most "
        f"{max(supported)}s -- re-adapt with shorter shots rather than truncating one"
    )


def resolve_parameters(
    capabilities, planned_duration_sec: float, preferred_resolution: str,
) -> ShotGenerationParameters:
    return ShotGenerationParameters(
        duration_sec=resolve_duration(capabilities, planned_duration_sec),
        resolution=resolve_resolution(capabilities, preferred_resolution),
        planned_duration_sec=planned_duration_sec,
    )


def select_reference_images(character, capabilities) -> list[Path]:
    """The approved reference views to attach to a generation, capped at
    what the provider accepts.

    Returns an empty list -- rather than raising -- when the provider does
    not support character references at all, or when the character has no
    approved sheet. The caller generates without them, which is what the
    fake tier has always done; refusing would break every offline run."""
    if character is None or not getattr(capabilities, "character_reference", False):
        return []
    # Approval is what the CHARACTER_REVIEW gate MEANS. An unapproved
    # sheet reaching paid generation would make the gate decorative.
    if not getattr(character, "reference_approved", False):
        return []
    images = getattr(character, "reference_images", None) or {}
    limit = getattr(capabilities, "max_character_references", 0) or 0
    if not getattr(capabilities, "multiple_references", False):
        limit = min(limit, 1)
    paths: list[Path] = []
    for view in REFERENCE_PRIORITY:
        if len(paths) >= limit:
            break
        raw = images.get(view)
        if not raw:
            continue
        path = Path(raw)
        # A recorded path whose file has since gone is skipped rather than
        # sent: the adapter would reject the request anyway, and losing
        # one view is better than losing the whole generation.
        if path.is_file():
            paths.append(path)
    return paths
