"""Hybrid pipeline: the real OpenAI-compatible LLM adapter (over a contract
MockTransport -- no external network, so this is wiring coverage, NOT a live
provider E2E) feeding the real policy/asset/TTS/render/validate pipeline with
fake asset+TTS providers and the real ffmpeg toolchain where present.
"""
from __future__ import annotations

import json

import httpx

from reel_harness.core.state_machine import JobStatus
from reel_harness.db.models import Job
from reel_harness.manifest.schema import ApprovalInfo, Manifest, is_publish_eligible
from reel_harness.media.deps import check_ffmpeg_available
from reel_harness.providers.fake_stock_media import FakeStockMediaProvider
from reel_harness.providers.fake_tts import FakeTTSProvider
from reel_harness.providers.openai_compatible_llm import OpenAICompatibleLLMProvider
from reel_harness.worker.runner import ProviderBundle, run_job

FFMPEG_PRESENT = check_ffmpeg_available().all_available

FAKE_KEY = "FAKE-HYBRID-E2E-KEY-000000000000"

SCRIPT_JSON = {
    "title": "3 pantry staples you are storing wrong",
    "scenes": [
        {
            "voiceover": f"Hybrid scene {i} voiceover, generated by the contract llm.",
            "subtitle": f"Scene {i}",
            "visual_query": f"pantry storage {i}",
            "duration_hint_sec": 4.0,
        }
        for i in range(3)
    ],
}


def _contract_llm() -> OpenAICompatibleLLMProvider:
    def handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            json={
                "id": "req-hybrid-1",
                "choices": [{"message": {"role": "assistant", "content": json.dumps(SCRIPT_JSON)}}],
                "usage": {"prompt_tokens": 111, "completion_tokens": 222, "total_tokens": 333},
            },
            headers={"x-request-id": "req-hybrid-1"},
        )

    return OpenAICompatibleLLMProvider(
        base_url="https://llm.example.invalid/v1", model="hybrid-model", api_key=FAKE_KEY,
        max_retries=0, retry_backoff_seconds=0.0, transport=httpx.MockTransport(handler),
    )


def _hybrid_bundle() -> ProviderBundle:
    return ProviderBundle(
        llm=_contract_llm(), tts=FakeTTSProvider(), stock_media=FakeStockMediaProvider(),
    )


def test_hybrid_pipeline_reaches_review_with_real_llm_metadata(
    job_service, channel, session_factory, storage,
) -> None:
    job, _ = job_service.create_job(channel.id, idempotency_key="hybrid-1", topic="pantry staples")
    with session_factory() as session:
        db_job = session.get(Job, job.id)
        run_job(session, db_job, channel, _hybrid_bundle(), storage)

        # The structured script came from the adapter and was schema-validated.
        assert db_job.script is not None
        assert db_job.script["title"] == SCRIPT_JSON["title"]
        assert db_job.script["llm_provider_id"] == "openai-compatible"
        assert db_job.script["llm_model_id"] == "hybrid-model"
        assert db_job.script["prompt_version"] == "openai-compat-script-v1"
        assert db_job.script["llm_request_id"] == "req-hybrid-1"
        assert db_job.script["llm_token_usage"]["total_tokens"] == 333
        assert FAKE_KEY not in json.dumps(db_job.script)

        if not FFMPEG_PRESENT:
            assert db_job.status == JobStatus.FAILED.value
            assert db_job.failure_code == "BLOCKED_DEPENDENCY"
            return
        assert db_job.status == JobStatus.REVIEW_REQUIRED.value

    manifest_raw = storage.read_bytes(job.id, "manifest.json")
    assert FAKE_KEY.encode() not in manifest_raw, "the API key must never reach the manifest"
    manifest = Manifest.model_validate_json(manifest_raw)
    assert manifest.llm.provider_id == "openai-compatible"
    assert manifest.llm.model_id == "hybrid-model"
    assert manifest.llm.prompt_version == "openai-compat-script-v1"
    assert manifest.validation.video_codec == "h264"
    assert manifest.validation.audio_codec == "aac"
    assert manifest.final_video_checksum_sha256 is not None

    # Fake assets carry FAKE_TEST_LICENSE: even a (simulated) approval must
    # never make this publish-eligible.
    assert is_publish_eligible(manifest) is False
    approved = manifest.model_copy(deep=True)
    approved.approval = ApprovalInfo(decision="approve", decided_at=manifest.created_at)
    assert is_publish_eligible(approved) is False


def test_reject_and_resume_keep_using_the_same_llm_wiring(
    job_service, channel, session_factory, storage,
) -> None:
    """Reject-to-SCRIPT re-runs the script stage through the same adapter
    bundle -- the regenerated script metadata stays consistent with the
    original provider/model, and the pipeline reaches review again."""
    job, _ = job_service.create_job(channel.id, idempotency_key="hybrid-2", topic="pantry staples")
    with session_factory() as session:
        db_job = session.get(Job, job.id)
        run_job(session, db_job, channel, _hybrid_bundle(), storage)
        if db_job.status != JobStatus.REVIEW_REQUIRED.value:
            assert db_job.failure_code == "BLOCKED_DEPENDENCY"  # honest no-ffmpeg outcome
            return

    job_service.reject(job.id, reason="rewrite the hook", regenerate_from_stage="SCRIPT")
    with session_factory() as session:
        db_job = session.get(Job, job.id)
        run_job(session, db_job, channel, _hybrid_bundle(), storage)
        assert db_job.status == JobStatus.REVIEW_REQUIRED.value
        assert db_job.script["llm_provider_id"] == "openai-compatible"
        assert db_job.script["llm_model_id"] == "hybrid-model"

    manifest = Manifest.model_validate_json(storage.read_bytes(job.id, "manifest.json"))
    assert manifest.llm.model_id == "hybrid-model"
