from __future__ import annotations

from pathlib import Path
from typing import Protocol


class StorageBackend(Protocol):
    def job_dir(self, job_id: str) -> Path: ...
    def path_for(self, job_id: str, rel_path: str) -> Path: ...
    def write_bytes(self, job_id: str, rel_path: str, data: bytes) -> Path: ...
    def read_bytes(self, job_id: str, rel_path: str) -> bytes: ...
    def exists(self, job_id: str, rel_path: str) -> bool: ...
